# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    docker:
      # specify the version you desire here
      - image: circleci/node:11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build
      - run: yarn run prod

      # deploy
      - run:
          name: configure git account
          command: |
            git config user.email "yuizho3@gmail.com"
            git config user.name "yuizho-circleci"
      - run:
          name: git commit & push (deploy)
          command: |
            if [ -n "$(git status --porcelain)" ]; then
              echo 'start deployment'
              git add -A
              git commit -m "[skip ci] deploy production archivement"
              git push origin master
            else
              echo 'skip deployment'
            fi
